export const weddings = [
  {
    id: 'anderson-kim',
    couple: 'Anderson & Kim',
    date: 'Jun 14, 2025',
    daysAway: 87,
    budget: 68000,
    guestCount: 180,
    progress: 62,
    color: '#C4705A',
    status: 'soon',
    statusLabel: '87 days away',
    vendors: [
      { name: 'Bloom & Garden',   category: 'Florals',       quote: 4800,  status: 'confirmed', initials: 'BG', color: '#8FAB8A' },
      { name: 'Lens & Petal',     category: 'Photography',   quote: 7200,  status: 'confirmed', initials: 'LP', color: '#C4705A' },
      { name: 'Rossini Catering', category: 'Catering',      quote: 18500, status: 'pending',   initials: 'RC', color: '#A8883A' },
      { name: 'SoundMasters DJ',  category: 'Music',         quote: null,  status: 'outreach',  initials: 'SM', color: '#6B8EC9' },
      { name: 'Grand Hall Venue', category: 'Venue',         quote: 12000, status: 'confirmed', initials: 'GH', color: '#B5748A' },
      { name: 'Sweet Layers',     category: 'Wedding Cake',  quote: 1800,  status: 'pending',   initials: 'SL', color: '#C4705A' },
    ],
    budget_breakdown: [
      { category: 'Venue',        amount: 12000, total: 12000, color: '#C4705A' },
      { category: 'Catering',     amount: 18500, total: 20000, color: '#A8883A' },
      { category: 'Photography',  amount: 7200,  total: 8000,  color: '#4D6B44' },
      { category: 'Florals',      amount: 4800,  total: 5000,  color: '#8FAB8A' },
      { category: 'Music',        amount: 0,     total: 3000,  color: '#B5748A' },
      { category: 'Cake & Other', amount: 1800,  total: 5000,  color: '#C8B9AC' },
    ],
    tasks: [
      { id: 1, title: 'Send save-the-dates',              done: true,  due: 'Done',      category: 'Stationery' },
      { id: 2, title: 'Follow up with SoundMasters DJ',   done: false, due: 'Tomorrow',  category: 'Music'      },
      { id: 3, title: 'Confirm guest dietary requirements', done: false, due: 'Mar 25',  category: 'Catering'   },
      { id: 4, title: 'Venue final payment',              done: false, due: 'Mar 22',    category: 'Venue'      },
      { id: 5, title: 'Bride makeup trial booking',       done: false, due: 'Apr 4',     category: 'Beauty'     },
      { id: 6, title: 'Finalise seating chart',           done: false, due: 'May 1',     category: 'Guests'     },
      { id: 7, title: 'Catering menu tasting',            done: false, due: 'Mar 28',    category: 'Catering'   },
      { id: 8, title: 'Order wedding favours',            done: false, due: 'Apr 15',    category: 'Decor'      },
    ],
    timeline: [
      { time: '8:00 AM',  title: 'Bridal suite opens',     sub: 'Hair & makeup team arrives · Sofía MUA', done: true,    current: false },
      { time: '10:30 AM', title: 'Photographer arrives',   sub: 'Getting ready shots · Lens & Petal',     done: true,    current: false },
      { time: '2:00 PM',  title: 'Ceremony begins',        sub: 'Grand Hall · Rev. Daniel Park',          done: false,   current: true  },
      { time: '4:00 PM',  title: 'Cocktail hour',          sub: 'Garden terrace · Rossini Catering',      done: false,   current: false },
      { time: '5:30 PM',  title: 'Reception & first dance', sub: 'Grand ballroom · SoundMasters DJ',      done: false,   current: false },
      { time: '10:00 PM', title: 'Last dance & farewell',  sub: 'Grand ballroom exit',                    done: false,   current: false },
    ],
    guests: [
      { name: 'James Anderson',   rsvp: 'confirmed', dietary: 'None',       table: 1 },
      { name: 'Lisa Kim',         rsvp: 'confirmed', dietary: 'Vegetarian', table: 1 },
      { name: 'Robert Chen',      rsvp: 'confirmed', dietary: 'None',       table: 2 },
      { name: 'Maria Garcia',     rsvp: 'pending',   dietary: 'Gluten-free', table: null },
      { name: 'David Park',       rsvp: 'confirmed', dietary: 'None',       table: 2 },
      { name: 'Sarah Johnson',    rsvp: 'declined',  dietary: 'None',       table: null },
      { name: 'Michael Lee',      rsvp: 'confirmed', dietary: 'Vegan',      table: 3 },
      { name: 'Emma Wilson',      rsvp: 'pending',   dietary: 'None',       table: null },
    ],
  },
  {
    id: 'martinez-osei',
    couple: 'Martínez & Osei',
    date: 'Aug 2, 2025',
    daysAway: 136,
    budget: 52000,
    guestCount: 120,
    progress: 41,
    color: '#4D6B44',
    status: 'upcoming',
    statusLabel: '136 days away',
    vendors: [],
    budget_breakdown: [],
    tasks: [],
    timeline: [],
    guests: [],
  },
  {
    id: 'patel-nguyen',
    couple: 'Patel & Nguyen',
    date: 'Sep 20, 2025',
    daysAway: 185,
    budget: 44000,
    guestCount: 95,
    progress: 18,
    color: '#A8883A',
    status: 'upcoming',
    statusLabel: '185 days away',
    vendors: [],
    budget_breakdown: [],
    tasks: [],
    timeline: [],
    guests: [],
  },
]

export const upcomingMilestones = [
  { day: '22', mon: 'Mar', title: 'Venue final payment',    sub: 'Anderson & Kim · Grand Hall',  tag: '3 days',  tagColor: '#C4705A', tagBg: '#F7EDE9' },
  { day: '28', mon: 'Mar', title: 'Catering menu tasting',  sub: 'Anderson & Kim · Rossini',     tag: '9 days',  tagColor: '#A8883A', tagBg: '#F5EDD8' },
  { day: '4',  mon: 'Apr', title: 'Bride makeup trial',     sub: 'Anderson & Kim · Sofía MUA',   tag: '16 days', tagColor: '#B5748A', tagBg: '#F3EAF0' },
  { day: '10', mon: 'Apr', title: 'Guest list deadline',    sub: 'Martínez & Osei',              tag: '22 days', tagColor: '#4D6B44', tagBg: '#EDF2EA' },
]
